Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 3df85ce] Automated commit from script - Updated Data
 4 files changed, 176 insertions(+), 387 deletions(-)
 rewrite logfile.log (76%)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   3d4a16d..3df85ce  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main ed86d84] Automated commit from script - Updated Data
 3 files changed, 183 insertions(+), 157 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   3df85ce..ed86d84  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 6ca435a] Automated commit from script - Updated Data
 3 files changed, 187 insertions(+), 157 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   ed86d84..6ca435a  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 434709b] Automated commit from script - Updated Data
 4 files changed, 4086 insertions(+), 157 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   6ca435a..434709b  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 005e2f7] Automated commit from script - Updated Data
 3 files changed, 392 insertions(+), 319 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   434709b..005e2f7  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.fresherstech.com/wipro-off-campus/,https://www.fresherstech.com/qualcomm-off-campus/,https://www.fresherstech.com/accenture-off-campus/,https://www.fresherstech.com/united-airlines-off-campus/,https://www.fresherstech.com/flowserve-off-campus/,https://www.fresherstech.com/amazon-off-campus/,https://www.fresherstech.com/beckman-coulter-diagnostics-internship/,https://www.fresherstech.com/pwc-off-campus/,https://www.fresherstech.com/ibm-off-campus/,https://www.fresherstech.com/allstate-off-campus/,https://www.fresherstech.com/crisil-internship/,https://www.fresherstech.com/hpe-off-campus/,https://www.fresherstech.com/citigroup-off-campus/,https://www.fresherstech.com/icf-off-campus/,https://www.fresherstech.com/abb-off-campus/,https://whatsapp.com/channel/0029VaABSZWEawdygYF5wI07,https://t.me/fresherstechofficial (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 6819f08] Automated commit from script - Updated Data
 3 files changed, 201 insertions(+), 170 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   005e2f7..6819f08  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://jobs.lever.co/zeotap/bd4ec452-d10b-4fcc-ba42-621bc93a1b6f/****,https://whatsapp.com/channel/0029Va5HM3OEAKWJT2QLQt33** (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 10f0caa] Automated commit from script - Updated Data
 3 files changed, 879 insertions(+), 738 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   6819f08..10f0caa  main -> main

Script ended.
Python script ran successfully. 
Server sent a very old message with ID 7401145571437042689, ignoring (see FAQ for details)
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 1e1a109] Automated commit from script - Updated Data
 3 files changed, 645 insertions(+), 619 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   10f0caa..1e1a109  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Server resent the older message 7402125358401631233, ignoring
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 4169708] Automated commit from script - Updated Data
 3 files changed, 388 insertions(+), 422 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   1e1a109..4169708  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main e2a14b8] Automated commit from script - Updated Data
 3 files changed, 716 insertions(+), 570 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   4169708..e2a14b8  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Max retries exceeded with url: /api/1QitLQLa?s=https://unstop.com/jobs/systems-engineer-i-honeywell-international-inc-1100471?utm_source=DotAware&utm_medium=Affiliates&utm_campaign=Honeywell01082024&ref=DAW****,https://whatsapp.com/channel/0029Va5HM3OEAKWJT2QLQt33** (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000016F47284B50>: Failed to resolve 'ouo.io' ([Errno 11001] getaddrinfo failed)"))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 72d67ad] Automated commit from script - Updated Data
 3 files changed, 1125 insertions(+), 1201 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   e2a14b8..72d67ad  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://myshopprime.com/Heeriye/aqgj8dw,https://myshopprime.com/Heeriye/aqgj8dw (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000023737C8C610>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Server resent the older message 7406983575243442177, ignoring
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 1ed14d1] Automated commit from script - Updated Data
 3 files changed, 2251 insertions(+), 2161 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   72d67ad..1ed14d1  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Automatic reconnection failed 5 time(s)
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection to Telegram failed 5 time(s)')>
ConnectionError: Connection to Telegram failed 5 time(s)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/pulse/stay-ahead-ai-enterprise-security-join-cybersentinel-anil-eyvvf/?trackingId=pZrB4tQoTHeUKwuzKXzLyw%3D%3D (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 53cbf2d] Automated commit from script - Updated Data
 3 files changed, 2138 insertions(+), 1850 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   1ed14d1..53cbf2d  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 6ad82e0] Automated commit from script - Updated Data
 3 files changed, 59 insertions(+), 72 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   53cbf2d..6ad82e0  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 902aece] Automated commit from script - Updated Data
 3 files changed, 208 insertions(+), 197 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   6ad82e0..902aece  main -> main

Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 838897e] Automated commit from script - Updated Data
 3 files changed, 60 insertions(+), 89 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   902aece..838897e  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main a2215ef] Automated commit from script - Updated Data
 3 files changed, 646 insertions(+), 457 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   838897e..a2215ef  main -> main

Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Automatic reconnection failed 5 time(s)
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection to Telegram failed 5 time(s)')>
ConnectionError: Connection to Telegram failed 5 time(s)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 34adcde] Automated commit from script - Updated Data
 3 files changed, 2238 insertions(+), 1473 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   a2215ef..34adcde  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/feed/update/urn:li:activity:7234839729135894528/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000002692392F010>: Failed to resolve 'ouo.io' ([Errno 11001] getaddrinfo failed)"))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main c417377] Automated commit from script - Updated Data
 3 files changed, 235 insertions(+), 270 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   34adcde..c417377  main -> main

Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 7abd956] Automated commit from script - Updated Data
 3 files changed, 589 insertions(+), 631 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   c417377..7abd956  main -> main

Script ended.
Python script ran successfully. 
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Telegram is having internal issues RpcMcgetFailError: Telegram is having internal issues, please try again later. (caused by GetHistoryRequest)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Request was unsuccessful 6 time(s)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 64] The specified network name is no longer available
Server closed the connection: [WinError 64] The specified network name is no longer available
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 752c25c] Automated commit from script - Updated Data
 3 files changed, 539 insertions(+), 280 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   7abd956..752c25c  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 65fc384] Automated commit from script - Updated Data
 3 files changed, 101 insertions(+), 98 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   752c25c..65fc384  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main bc4d630] Automated commit from script - Updated Data
 3 files changed, 579 insertions(+), 751 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   65fc384..bc4d630  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/feed/update/urn:li:activity:7236358143553761280/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/posts/insimran_sde-iii-backend-activity-7238813178267156480-zOBT?utm_source=share&utm_medium=member_android (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000019B7521AA50>: Failed to resolve 'ouo.io' ([Errno 11001] getaddrinfo failed)"))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://offcampusjobs4u.com/boston-consulting-group-bcg-hiring/**,https://bit.ly/48V2BTI****,https://bit.ly/3gaecrd****,https://telegram.me/offcampusjobs4u****,https://bit.ly/3WvWjTD** (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://tinyurl.com/9j2bbsn4,https://t.me/gulfvacanciesworld (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 65ddf71] Automated commit from script - Updated Data
 3 files changed, 1079 insertions(+), 1004 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   bc4d630..65ddf71  main -> main

Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://youtube.com/@qtomation) (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/posts/azim-premji-foundation_qualityeducation-publiceducation-socialsectorjobs-activity-7239852789844082688-_lpP?utm_source=share&utm_medium=member_desktop (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://offcampusjobs4u.com/quest-global-off-campus-drive-2024-hiring-for-trainee/**,https://bit.ly/48V2BTI****,https://bit.ly/3gaecrd****,https://telegram.me/offcampusjobs4u****,https://bit.ly/3WvWjTD** (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Server sent a very old message with ID 7419729256053031953, ignoring (see FAQ for details)
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Server sent a very old message with ID 7419729297894505473, ignoring (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://getngojobs.org/jobs/fundraising-and-communications-manager-ngo-jobs-in-india,https://getngojobs.org/jobs/grameen-sahayak-sales-officer-ngo-jobs-in-india-3322,https://getngojobs.org/jobs/grameen-sahayak-sales-officer-ngo-jobs-in-india,https://getngojobs.org/jobs/soft-skills-trainer-ngo-jobs-in-india,https://getngojobs.org/jobs/center-manager-ngo-jobs-in-india-3319,https://getngojobs.org/jobs/project-program-manager-ngo-jobs-in-india,https://getngojobs.org/jobs/trainer-ngo-jobs-in-india-3317,https://t.me/getngojob,https://www.linkedin.com/in/pradeep-pachouri-910b31228?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app,https://whatsapp.com/channel/0029VajloZx3QxS1o25Lz405 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/posts/ruchi-meena-768500176_jobsearch-recruitmenttips-careeradvice-activity-7238417976293531648-Mpiw,https://www.linkedin.com/posts/path-builder_hiring-fellows-fellowship-activity-7238760128164904960-vRRX?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/teach-for-india_join-us-as-a-design-intern-are-you-a-creative-activity-7238810188693094400-w1By?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/farhan-andaleeb-10019911_we-are-hiring-following-positions-are-currently-activity-7238873130725744640-_9W2?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/social-impact-and-development-communication-centre_hiringnow-hiring-jobsearch-activity-7238833618825994240-2BmI?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/jayant-ruthe-8770381ba_were-hiring-join-us-at-trrain-as-an-executive-activity-7237361087409471491-mugG?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/nisgsmartgov_consultant-corporate-communication-bbnl-activity-7238803727711621123-y72k?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/vvengadesan_udhyam-vyapaar-is-hiring-a-monitoring-evaluation-activity-7238842980189511682-UkOM?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/jenicobbsorensen_program-coordinator-ipa-sector-programs-activity-7238904286745653248-MV55?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/youthdreamersfoundation_hiringnow-joinourteam-careeropportunities-activity-7237783001177161728-FgH2?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/ennhri_humanrights-european-jobalert-activity-7238930410582286336-3cHo?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/feed/update/urn:li:activity:7238776595161739264/,https://www.linkedin.com/posts/isd-center_hiring-newjob-researcher-activity-7238803441039376385-psJP?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/feed/update/urn:li:activity:7236581291314290688/,https://www.linkedin.com/posts/archana-bhattacharya-a7118616_operations-ugcPost-7236694368944873472-4JBh?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/shreya-r-b0486820a_careers-activity-7239166851572727810-KwKf?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/satyender-singh_gev-hire-ugcPost-7238934597856641024-QPeN?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/shikshalokam_hiring-ui-designer-activity-7238848635604496385-Mgjb?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/village-social-transformation-foundation_taluka-coordinators-program-activity-7238219466969411584-O7ud?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/sustainable-futures-collaborative_hiring-activity-7238777957954035712-KPKE?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/the-samhita-academy-info_are-you-passionate-about-education-and-ready-activity-7237786133684740096-g8e-?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/shirin-kaul-469a081b2_education-teachercoaching-instructionaldesign-ugcPost-7237415640272125952-CGvL?utm_source=share&utm_medium=member_desktop,https://www.linkedin.com/posts/sejal-kandalgaonkar-83248a6a_hr-recruiter-activity-7239139714463629312-9c_z?utm_source=share&utm_medium=member_desktop (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/feed/update/urn:li:activity:7241773025371586560/ (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 368fd85] Automated commit from script - Updated Data
 3 files changed, 5005 insertions(+), 5066 deletions(-)
 rewrite data/main_messages1.json (60%)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   65ddf71..368fd85  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/feed/update/urn:li:activity:7246464218688839680/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_recent_activity_content_view%3B8JvYDcSzRzWVIi%2BPjMC5OA%3D%3D (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main bb60173] Automated commit from script - Updated Data
 3 files changed, 278 insertions(+), 483 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   368fd85..bb60173  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 2320520] Automated commit from script - Updated Data
 3 files changed, 57 insertions(+), 33 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   bb60173..2320520  main -> main

Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Server resent the older message 7421618632775584769, ignoring
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.linkedin.com/posts/pradeep-pachouri-910b31228_hiring-org-location-activity-7246482010486022145-1L1Z?utm_source=share&utm_medium=member_android (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001378F3DC110>: Failed to establish a new connection: [WinError 10065] A socket operation was attempted to an unreachable host'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main a207c6e] Automated commit from script - Updated Data
 3 files changed, 359 insertions(+), 492 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   2320520..a207c6e  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 5ad8623] Automated commit from script - Updated Data
 3 files changed, 67 insertions(+), 44 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   a207c6e..5ad8623  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 2668891] Automated commit from script - Updated Data
 3 files changed, 213 insertions(+), 186 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   5ad8623..2668891  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 465ec4b] Automated commit from script - Updated Data
 3 files changed, 67 insertions(+), 44 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   2668891..465ec4b  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 10054] An existing connection was forcibly closed by the remote host
Server sent a very old message with ID 7422641140237682689, ignoring (see FAQ for details)
Server resent the older message 7422973131827020801, ignoring
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main f56bfab] Automated commit from script - Updated Data
 3 files changed, 193 insertions(+), 288 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   465ec4b..f56bfab  main -> main

Script ended.
Python script ran successfully. 
