Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
Script started.
Traceback (most recent call last):
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 738, in <module>
    log_message("Script started.")
  File "D:\Projects\JobFinder\backend\mainScraper.py", line 733, in log_message
    with open(log_file, 'a') as f:
         ^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Projects\\JobFinder\\backend\\logfile.log'
Python script encountered an error. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 3df85ce] Automated commit from script - Updated Data
 4 files changed, 176 insertions(+), 387 deletions(-)
 rewrite logfile.log (76%)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   3d4a16d..3df85ce  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main ed86d84] Automated commit from script - Updated Data
 3 files changed, 183 insertions(+), 157 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   3df85ce..ed86d84  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 6ca435a] Automated commit from script - Updated Data
 3 files changed, 187 insertions(+), 157 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   ed86d84..6ca435a  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 434709b] Automated commit from script - Updated Data
 4 files changed, 4086 insertions(+), 157 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   6ca435a..434709b  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 005e2f7] Automated commit from script - Updated Data
 3 files changed, 392 insertions(+), 319 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   434709b..005e2f7  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://www.fresherstech.com/wipro-off-campus/,https://www.fresherstech.com/qualcomm-off-campus/,https://www.fresherstech.com/accenture-off-campus/,https://www.fresherstech.com/united-airlines-off-campus/,https://www.fresherstech.com/flowserve-off-campus/,https://www.fresherstech.com/amazon-off-campus/,https://www.fresherstech.com/beckman-coulter-diagnostics-internship/,https://www.fresherstech.com/pwc-off-campus/,https://www.fresherstech.com/ibm-off-campus/,https://www.fresherstech.com/allstate-off-campus/,https://www.fresherstech.com/crisil-internship/,https://www.fresherstech.com/hpe-off-campus/,https://www.fresherstech.com/citigroup-off-campus/,https://www.fresherstech.com/icf-off-campus/,https://www.fresherstech.com/abb-off-campus/,https://whatsapp.com/channel/0029VaABSZWEawdygYF5wI07,https://t.me/fresherstechofficial (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 6819f08] Automated commit from script - Updated Data
 3 files changed, 201 insertions(+), 170 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   005e2f7..6819f08  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Max retries exceeded with url: /api/1QitLQLa?s=https://jobs.lever.co/zeotap/bd4ec452-d10b-4fcc-ba42-621bc93a1b6f/****,https://whatsapp.com/channel/0029Va5HM3OEAKWJT2QLQt33** (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Security error while unpacking a received message: Server replied with a wrong session ID (see FAQ for details)
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 10f0caa] Automated commit from script - Updated Data
 3 files changed, 879 insertions(+), 738 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   6819f08..10f0caa  main -> main

Script ended.
Python script ran successfully. 
Server sent a very old message with ID 7401145571437042689, ignoring (see FAQ for details)
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 1e1a109] Automated commit from script - Updated Data
 3 files changed, 645 insertions(+), 619 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   10f0caa..1e1a109  main -> main

Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Server resent the older message 7402125358401631233, ignoring
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Server closed the connection: [WinError 121] The semaphore timeout period has expired
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Attempt 5 at connecting failed: TimeoutError: 
Attempt 6 at connecting failed: TimeoutError: 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main 4169708] Automated commit from script - Updated Data
 3 files changed, 388 insertions(+), 422 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   1e1a109..4169708  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: TimeoutError: 
Attempt 4 at connecting failed: ConnectionAbortedError: [WinError 1236] The network connection was aborted by the local system
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 1 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
Disconnecting Telegram client
Writing data to D:\Projects\JobFinder\backend\data\main_messages1.json
New instance of Robo created and data saved
Running git add


Running git commit
[main e2a14b8] Automated commit from script - Updated Data
 3 files changed, 716 insertions(+), 570 deletions(-)


Running git push

To https://github.com/shubh1712/job-finder-backend.git
   4169708..e2a14b8  main -> main

Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: TimeoutError: 
Attempt 2 at connecting failed: TimeoutError: 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPConnectionPool(host='ouo.io', port=80): Max retries exceeded with url: /api/1QitLQLa?s=https://unstop.com/jobs/systems-engineer-i-honeywell-international-inc-1100471?utm_source=DotAware&utm_medium=Affiliates&utm_campaign=Honeywell01082024&ref=DAW****,https://whatsapp.com/channel/0029Va5HM3OEAKWJT2QLQt33** (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000016F47284B50>: Failed to resolve 'ouo.io' ([Errno 11001] getaddrinfo failed)"))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Server closed the connection: [WinError 1236] The network connection was aborted by the local system
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))
Script ended.
Python script ran successfully. 
^CScript started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1231] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: HTTPSConnectionPool(host='ouo.io', port=443): Read timed out. (read timeout=None)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
Attempt 1 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 2 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 3 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 4 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 5 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Attempt 6 at connecting failed: OSError: [WinError 1232] The network location cannot be reached. For information about network troubleshooting, see Windows Help
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: Connection to Telegram failed 5 time(s)
Script ended.
Python script ran successfully. 
Script started.
Reading chat data from D:\Projects\JobFinder\backend\data\chat_data.json
Fetched chat IDs
Initiating emergency self destroy protocol...
Starting Telegram client
An error occurred: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Script ended.
Python script ran successfully. 
